baseURL = "https://stewartshea.github.io/hugotest/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "RunWhen"
# Main Menu
[[menu.main]]
name = "What is RunWhen?"
url = "#home"
weight = 1
[[menu.main]]
name = "Who is it for?"
url = "#who"
weight = 2
[[menu.main]]
name = "When can I try it?"
url = "#when"
weight = 3


# Sitemap Menu
[[menu.sitemap]]
name = "What is RunWhen?"
url = "#home"
weight = 1
[[menu.sitemap]]
name = "Who is it for?"
url = "#who"
[[menu.sitemap]]
name = "When can I try it?"
url = "#when"
weight = 3


[params]
betaLink = "beta"
copyright = "All right reserved copyright © RunWhen 2022"
footerLogo = "images/contact/widget-logo.png"
getformURL = "https://getform.io/f/7r9y1"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

